### PR TITLE
Update Uno Version to 2.0.236-dev.2800

### PR DESCRIPTION
**Pull request by michael-hawker**
Wanted to separate out the needed update from PR #59 as I was having trouble building on my local machine, think was VS mangling the conditional includes... 😒

Will see what the CI does here.

### CODE REVIEW

**Comment by agneszitte** [comment]
build succeeded @michael-hawker ;)

**Comment by michael-hawker** [comment]
Yay! I'll see if I can build locally and try out the sample app to make sure nothing seems functionally broken.  Then we can merge, I'll update my other PR, and then can test that for the graph stuff... slowly but surely, eh? ☺

**Comment by michael-hawker** [comment]
Hmm, was able to do `msbuild /restore` on the command-line ok, but then trying to run the UWP sample app gave me 4 copies of this error:

```
C:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Shared\Pages\SampleController.xaml(343,26): XamlCompiler error WMC0001: Unknown type 'PaneStateTrigger' in XML namespace 'clr-namespace:Microsoft.Toolkit.Uwp.SampleApp.Shared.Triggers;assembly=Microsoft.Toolkit.Uwp.SampleApp, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null'
1>  
```

Looks like it's because [this line](https://github.com/unoplatform/Uno.WindowsCommunityToolkit/blob/uno/Microsoft.Toolkit.Uwp.SampleApp.Shared/Pages/SampleController.xaml#L16) is using clr-namespace instead of `using` as part of #58. @XiaotianNetlift is this something you can fix and ensure the sample app still runs off the main `uno` branch? Thanks!

I also get this at runtime:
```
System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
```

**Comment by XiaotianNetlift** [comment]
@michael-hawker 
There are still a few other issues with the uwp build that haven't been really investigated:
- BannerControl causing E_FAIL in MeasureOverride
- missing resources:
  ```
  Cannot find a Resource with the Name/Key NavigationViewSettingsItemStyleWhenOnTopPane [Line: 1251 Position: 95]
  Cannot find a Resource with the Name/Key NavigationViewItemPresenterStyleWhenOnTopPane [Line: 605 Position: 92]
  Cannot find a Resource with the Name/Key NavigationViewItemPresenterStyleWhenOnLeftPane [Line: 600 Position: 92]
  ```
- NavigationView ("TopNavMenuItemsHost") items has no width/data template not working (even one with hardcoded size doesn't work)

The workaround for the first two issues can be found on this branch: https://github.com/unoplatform/Uno.WindowsCommunityToolkit/commits/dev/xygu/dont-delete/20190930/uwp-workarounds
However, the last one still remains unsolved, but at least the app is running with no crash.


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/unoplatform/Uno.WindowsCommunityToolkit">unoplatform/Uno.WindowsCommunityToolkit</a></strong></div><div>The Windows Community Toolkit is a collection of helper functions, custom controls, and app services. It simplifies and demonstrates common developer tasks building UWP apps for Windows 10. The too...</div></blockquote>

**Comment by michael-hawker** [comment]
@agneszitte-nventive @XiaotianNetlift think we should just merge this in and then I can update my other PR and test that more thoroughly all together.  That should be easier.

**Comment by jeromelaban** [comment]
Yes, let's do that for now.

**Pull request merged**
