### PR TITLE
Add Android SamplesApp head

### PR DESCRIPTION
**Pull request by davidjohnoliver**
This allows the samples to be run and viewed on Android.

Issue: #

## PR Type
What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../readme.md#supported)
- [ ] Pull Request has been submitted to the documentation repository [instructions](..\contributing.md#docs). Link: 
- [ ] Sample in sample app has been added / updated (for bug fixes / features)
    - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Header has been added to all new source files (run *build/UpdateHeaders.bat*)
- [x] Contains **NO** breaking changes

### CODE REVIEW

**Comment by michael-hawker** [comment]
@davidjohnoliver what's the difference between the `Windows Community Toolkit.Uno.sln` and the the `Windows Community Toolkit.sln`.  I was trying to build the .Uno one at first, but if the main one is the correct one, should the other one be removed?

**Comment by michael-hawker** [comment]
@davidjohnoliver I'm also getting a bunch of these errors on build:

```
11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.targetsize-16.png(1): error APT0000: Resource entry uwpcommunitytoolkitsampleappapplist is already defined.
11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.png(1): error APT0000: Originally defined here.
11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.targetsize-16_altform-unplated.png(1): error APT0000: Resource entry uwpcommunitytoolkitsampleappapplist is already defined.
11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.png(1): error APT0000: Originally defined here.
11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.targetsize-20.png(1): error APT0000: Resource entry uwpcommunitytoolkitsampleappapplist is already defined.
11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.png(1): error APT0000: Originally defined here.
```

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver what's the difference between the `Windows Community Toolkit.Uno.sln` and the the `Windows Community Toolkit.sln`. I was trying to build the .Uno one at first, but if the main one is the correct one, should the other one be removed?

This is a good question that I'll pose to @jeromelaban once he's back. The main solution has been modified recently on the 'uno' branch, whereas the `.Uno.sln` one was only touched once, which is why I went with the former. It's possible that Jerome created it and just forgot to remove it.

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver I'm also getting a bunch of these errors on build:
> 
> ```
> 11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.targetsize-16.png(1): error APT0000: Resource entry uwpcommunitytoolkitsampleappapplist is already defined.
> 11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.png(1): error APT0000: Originally defined here.
> 11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.targetsize-16_altform-unplated.png(1): error APT0000: Resource entry uwpcommunitytoolkitsampleappapplist is already defined.
> 11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.png(1): error APT0000: Originally defined here.
> 11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.targetsize-20.png(1): error APT0000: Resource entry uwpcommunitytoolkitsampleappapplist is already defined.
> 11>  H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\res\drawable-mdpi-v4\uwpcommunitytoolkitsampleappapplist.png(1): error APT0000: Originally defined here.
> ```

I [created an issue](https://github.com/unoplatform/uno/issues/1370) for this. The workaround for now is to locally delete the assets with 'targetsize' in their filename. The problem is that the Uno build task that converts assets to Android format is not handling them properly.

**Comment by michael-hawker** [comment]
Thanks @davidjohnoliver, that seemed to work better, but as I tried to remove the NavigationView in the XAML it started giving me a ton of other code-behind errors.  Do you have a stripped branch you can share that compiles with all the currently needed work-arounds?

It's fine if I just have to manually instantiate controls in Shell.xaml or if it's just to a fixed page in a frame of a specific sample.

**Comment by davidjohnoliver** [comment]
> Thanks @davidjohnoliver, that seemed to work better, but as I tried to remove the NavigationView in the XAML it started giving me a ton of other code-behind errors. Do you have a stripped branch you can share that compiles with all the currently needed work-arounds?
> 
> It's fine if I just have to manually instantiate controls in Shell.xaml or if it's just to a fixed page in a frame of a specific sample.

Sure, here's a stripped-down version of the shell that builds and runs successfully on Android: https://github.com/unoplatform/Uno.WindowsCommunityToolkit/tree/dev/djo/stripped-down-sample

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/unoplatform/Uno.WindowsCommunityToolkit">unoplatform/Uno.WindowsCommunityToolkit</a></strong></div><div>The Windows Community Toolkit is a collection of helper functions, custom controls, and app services. It simplifies and demonstrates common developer tasks building UWP apps for Windows 10. The too...</div></blockquote>

**Comment by michael-hawker** [comment]
@davidjohnoliver thanks, getting closer!

```
Unhandled Exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. occurred

 	0x1A in System.Reflection.MonoCMethod.InternalInvoke	C#
 	0x88 in System.Reflection.MonoCMethod.DoInvoke	C#
 	0x7 in System.Reflection.MonoCMethod.Invoke	C#
 	0x12 in System.Reflection.ConstructorInfo.Invoke	C#
 	0x6F in Java.Interop.TypeManager.CreateProxy	C#
 	0x119 in Java.Interop.TypeManager.CreateInstance	C#
 	0xC4 in Java.Lang.Object.GetObject	C#
 	0x23 in Java.Lang.Object._GetObject<Android.Content.Context>	C#
 	0x2 in Java.Lang.Object.GetObject<Android.Content.Context>	C#
 	0x33 in Android.App.Application.get_Context	C#
 	0x14 in Android.App.SyncContext.Post	C#
 	0x33 in Xamarin.InspectorSupport.<>c.<StartBreakdance>b__5_0 at C:\vsts\_work\5\s\Agents\Xamarin.Interactive.Android\InspectorSupport.cs:41,21	C#
 	0x13 in System.Threading.Timer.Scheduler.TimerCB	C#
 	0x1B in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem	C#
 	0x75 in System.Threading.ThreadPoolWorkQueue.Dispatch	C#
 	0x0 in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback	C#
```

I'm trying API 26 should I use a different one now?

I'm also trying to build the iOS one on a Mac now, but get an error from Mono about language targets for uap16299 are missing in `CheckMissing.targets`?  Am I missing a tooling dependency?

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver thanks, getting closer!
> 
> ```
> Unhandled Exception:
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. occurred
> 
>  	0x1A in System.Reflection.MonoCMethod.InternalInvoke	C#
>  	0x88 in System.Reflection.MonoCMethod.DoInvoke	C#
>  	0x7 in System.Reflection.MonoCMethod.Invoke	C#
>  	0x12 in System.Reflection.ConstructorInfo.Invoke	C#
>  	0x6F in Java.Interop.TypeManager.CreateProxy	C#
>  	0x119 in Java.Interop.TypeManager.CreateInstance	C#
>  	0xC4 in Java.Lang.Object.GetObject	C#
>  	0x23 in Java.Lang.Object._GetObject<Android.Content.Context>	C#
>  	0x2 in Java.Lang.Object.GetObject<Android.Content.Context>	C#
>  	0x33 in Android.App.Application.get_Context	C#
>  	0x14 in Android.App.SyncContext.Post	C#
>  	0x33 in Xamarin.InspectorSupport.<>c.<StartBreakdance>b__5_0 at C:\vsts\_work\5\s\Agents\Xamarin.Interactive.Android\InspectorSupport.cs:41,21	C#
>  	0x13 in System.Threading.Timer.Scheduler.TimerCB	C#
>  	0x1B in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem	C#
>  	0x75 in System.Threading.ThreadPoolWorkQueue.Dispatch	C#
>  	0x0 in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback	C#
> ```
> 
> I'm trying API 26 should I use a different one now?
> 
> I'm also trying to build the iOS one on a Mac now, but get an error from Mono about language targets for uap16299 are missing in `CheckMissing.targets`? Am I missing a tooling dependency?

Hmm... are you able to break on the exception and see what the actual `InnerException` is?

And your iOS error is puzzling, I don't know why Mono would be trying to check for UAP language targets. As a sanity check are you able to build and run a [blank Uno ](https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin)app on iOS?

**Comment by michael-hawker** [comment]
Turned on breaking on all exceptions and got this in the `App.xaml.cs` contructor:

```
Exception:

System.TypeInitializationException: The type initializer for 'Windows.UI.Core.CoreDispatcher' threw an exception. occurred
 	0x7 in Windows.UI.Xaml.Window.InternalGetCurrentWindow at D:\a\1\s\src\Uno.UI\UI\Xaml\Window.Android.cs:69,5	C#
 	0x0 in Windows.UI.Xaml.Window.get_Current at D:\a\1\s\src\Uno.UI\UI\Xaml\Window.cs:53,35	C#
 	0x21 in Windows.UI.Xaml.Application..ctor at D:\a\1\s\src\Uno.UI\UI\Xaml\Application.Android.cs:16,4	C#
>	0x1 in Microsoft.Toolkit.Uwp.SampleApp.App..ctor at H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Shared\App.xaml.cs:36,9	C#
 	0x1 in Microsoft.Toolkit.Uwp.SampleApp.Droid.Application..ctor at H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\Main.cs:27,15	C#
 	0xFFFFFFFFFFFFFFFF in System.Reflection.MonoCMethod.InternalInvoke	C#
 	0xA in System.Reflection.MonoCMethod.InternalInvoke	C#
 	0x88 in System.Reflection.MonoCMethod.DoInvoke	C#
 	0x7 in System.Reflection.MonoCMethod.Invoke	C#
 	0x12 in System.Reflection.ConstructorInfo.Invoke	C#
 	0x6F in Java.Interop.TypeManager.CreateProxy	C#
 	0x119 in Java.Interop.TypeManager.CreateInstance	C#
 	0xC4 in Java.Lang.Object.GetObject	C#
 	0x23 in Java.Lang.Object._GetObject<Android.Content.Context>	C#
 	0x2 in Java.Lang.Object.GetObject<Android.Content.Context>	C#
 	0x33 in Android.App.Application.get_Context	C#
 	0x14 in Android.App.SyncContext.Post	C#
 	0x33 in Xamarin.InspectorSupport.<>c.<StartBreakdance>b__5_0 at C:\vsts\_work\5\s\Agents\Xamarin.Interactive.Android\InspectorSupport.cs:41,21	C#
 	0x13 in System.Threading.Timer.Scheduler.TimerCB	C#
 	0x1B in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem	C#
 	0x75 in System.Threading.ThreadPoolWorkQueue.Dispatch	C#
 	0x0 in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback	C#
```

It unfortunately isn't giving me many options to see into the exception itself though for some reason.

Yup the iOS project of the initial Uno template works fine on the Mac as expected.  I think part of the difference is the MSBuild SDK Extras project format?  I don't actually see the option to run the iOS project either, though the build errors are the first step. @jeromelaban does it work on your machine?

**Comment by davidjohnoliver** [comment]
> Turned on breaking on all exceptions and got this in the `App.xaml.cs` contructor:
> 
> ```
> Exception:
> 
> System.TypeInitializationException: The type initializer for 'Windows.UI.Core.CoreDispatcher' threw an exception. occurred
>  	0x7 in Windows.UI.Xaml.Window.InternalGetCurrentWindow at D:\a\1\s\src\Uno.UI\UI\Xaml\Window.Android.cs:69,5	C#
>  	0x0 in Windows.UI.Xaml.Window.get_Current at D:\a\1\s\src\Uno.UI\UI\Xaml\Window.cs:53,35	C#
>  	0x21 in Windows.UI.Xaml.Application..ctor at D:\a\1\s\src\Uno.UI\UI\Xaml\Application.Android.cs:16,4	C#
> >	0x1 in Microsoft.Toolkit.Uwp.SampleApp.App..ctor at H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Shared\App.xaml.cs:36,9	C#
>  	0x1 in Microsoft.Toolkit.Uwp.SampleApp.Droid.Application..ctor at H:\code\Uno.WindowsCommunityToolkit\Microsoft.Toolkit.Uwp.SampleApp.Droid\Main.cs:27,15	C#
>  	0xFFFFFFFFFFFFFFFF in System.Reflection.MonoCMethod.InternalInvoke	C#
>  	0xA in System.Reflection.MonoCMethod.InternalInvoke	C#
>  	0x88 in System.Reflection.MonoCMethod.DoInvoke	C#
>  	0x7 in System.Reflection.MonoCMethod.Invoke	C#
>  	0x12 in System.Reflection.ConstructorInfo.Invoke	C#
>  	0x6F in Java.Interop.TypeManager.CreateProxy	C#
>  	0x119 in Java.Interop.TypeManager.CreateInstance	C#
>  	0xC4 in Java.Lang.Object.GetObject	C#
>  	0x23 in Java.Lang.Object._GetObject<Android.Content.Context>	C#
>  	0x2 in Java.Lang.Object.GetObject<Android.Content.Context>	C#
>  	0x33 in Android.App.Application.get_Context	C#
>  	0x14 in Android.App.SyncContext.Post	C#
>  	0x33 in Xamarin.InspectorSupport.<>c.<StartBreakdance>b__5_0 at C:\vsts\_work\5\s\Agents\Xamarin.Interactive.Android\InspectorSupport.cs:41,21	C#
>  	0x13 in System.Threading.Timer.Scheduler.TimerCB	C#
>  	0x1B in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem	C#
>  	0x75 in System.Threading.ThreadPoolWorkQueue.Dispatch	C#
>  	0x0 in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback	C#
> ```
> 
> It unfortunately isn't giving me many options to see into the exception itself though for some reason.
> 
> Yup the iOS project of the initial Uno template works fine on the Mac as expected. I think part of the difference is the MSBuild SDK Extras project format? I don't actually see the option to run the iOS project either, though the build errors are the first step. @jeromelaban does it work on your machine?

For Android - I am curious, does it work if you launch the app without the debugger attached? The `Xamarin.InspectorSupport.<>c.<StartBreakdance>` method is associated with the debugger and we've had problems in the past where it runs 'too early' and calls the `Application` ctor on a background thread instead of the UI thread.

**Comment by michael-hawker** [comment]
🦙❤ @davidjohnoliver magic happened! 😊 I'll copy in my other test code now and see what happens next. 😉

Is this a Xamarin bug then that we need to track?  Do you have an issue open with them already?

**Comment by davidjohnoliver** [comment]
> 🦙❤ @davidjohnoliver magic happened! 😊 I'll copy in my other test code now and see what happens next. 😉
> 
> Is this a Xamarin bug then that we need to track? Do you have an issue open with them already?

I don't think we opened an issue yet, no. Previously we [worked around it](https://github.com/unoplatform/Uno/commit/a219404d).

**Comment by michael-hawker** [comment]
So would updating the version of the Uno dependency help fix this or is this another instance of the issue for other reasons?

Or is there some way I can delay the construction so that I can still debug?

**Comment by davidjohnoliver** [comment]
> So would updating the version of the Uno dependency help fix this or is this another instance of the issue for other reasons?

The latter, unfortunately. 

Are you able to try a recent version of Visual Studio? (I think you mentioned you were using 2017.) If you still get the bug, I'll open an issue with Xamarin.Android. (If not - yay!)

Another workaround-ish thing to try is to try debugging on physical device if you're currently using an emulator (or vice versa), from memory that may help.

**Comment by michael-hawker** [comment]
Thanks David, I can try 2019, but we were hitting an issue before with the toolkit and the MSBuild Extras project due to a regression before.  But if you were testing there yourself, maybe it's resolved.  I'll try it out and let you know.

**Comment by michael-hawker** [comment]
@davidjohnoliver 2019 seems to be working for debugging, yay! 🦙❤

I am noticing my App.xaml isn't being initialized though, so I think I have an understanding gap.  I'm guessing the gitter channel is a good place for that?

**Review by carldebilly — APPROVED** [review]

**Pull request merged**
